source 'https://github.com/CocoaPods/Specs.git'

pod 'AWSCore'
pod 'AWSS3'
pod 'AWSSimpleDB'
pod 'AWSCognito'
pod 'RNCryptor'
pod 'Bolts'
pod 'Reachability'
pod 'Parse', '~> 1.8.2'
pod 'SDWebImage'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'BlocksKit'
