//
//  AWSTwitterSignInProvider.m
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import "AWSTwitterSignInProvider.h"
#import <AWSCore/AWSCore.h>
#import "AWSIdentityManager.h"

#import <TwitterKit/TwitterKit.h>

NSString *const AWSTwitterSignInProviderKey = @"Twitter";
NSString *const AWSTwitterSignInProviderUserNameKey = @"Twitter.userName";
NSString *const AWSTwitterSignInProviderUserIDKey = @"Twitter.userID";

@interface AWSIdentityManager()

- (void)completeLogin:(NSDictionary *)logins;

@end

@interface AWSTwitterSignInProvider()

@property (strong, nonatomic) NSString *userName;

@end

@implementation AWSTwitterSignInProvider

+ (instancetype)sharedInstance {
    static AWSTwitterSignInProvider *_sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedInstance = [AWSTwitterSignInProvider new];
    });

    return _sharedInstance;
}

- (BOOL)isLoggedIn {
    BOOL loggedIn = [Twitter sharedInstance].session;
    return [[NSUserDefaults standardUserDefaults] objectForKey:AWSTwitterSignInProviderKey] != nil && loggedIn;
}

- (NSString *)userName {
    return [[NSUserDefaults standardUserDefaults] objectForKey:AWSTwitterSignInProviderUserNameKey];
}

- (void)setUserName:(NSString *)userName {
    [[NSUserDefaults standardUserDefaults] setObject:userName
                                              forKey:AWSTwitterSignInProviderUserNameKey];
}


- (NSString *)userID {
    return [[NSUserDefaults standardUserDefaults] objectForKey:AWSTwitterSignInProviderUserIDKey];
}

- (void)setUserID:(NSString *)userID {
    [[NSUserDefaults standardUserDefaults] setObject:userID
                                              forKey:AWSTwitterSignInProviderUserIDKey];
}


- (void)reloadSession {
    if ([[NSUserDefaults standardUserDefaults] objectForKey:AWSTwitterSignInProviderKey]
        && [Twitter sharedInstance].session) {
        [self completeLogin];
    }
}

- (void)completeLogin {
    [[NSUserDefaults standardUserDefaults] setObject:@"YES"
                                              forKey:AWSTwitterSignInProviderKey];
    
    TWTRSession *session = [Twitter sharedInstance].session;
    NSString *value = [NSString stringWithFormat:@"%@;%@",session.authToken,session.authTokenSecret];
    [[AWSIdentityManager sharedInstance] completeLogin:@{@"api.twitter.com": value}];
    
    self.userName = session.userName;
    self.userID = session.userID;
    

}

- (void)login {
    if ([Twitter sharedInstance].session) {
        [self completeLogin];
        return;
    }
    
    [[Twitter sharedInstance] logInWithCompletion:^(TWTRSession *session, NSError *error) {
        if (session) {
            NSLog(@"logged in user with id %@", session.userID);
            [self completeLogin];
        } else {
            NSLog(@"Failure to log in Twitter account");
        }
    }];
    
    
    
}

- (void)logout {
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:AWSTwitterSignInProviderKey];
    if ([Twitter sharedInstance].session) {
        [[Twitter sharedInstance] logOut];
    }
}

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    return NO;
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    return NO;
}

@end
